'use client';

import { useState, useEffect } from 'react';
import { useParams } from 'next/navigation';
import { useQuery } from '@tanstack/react-query';
import { appsApi, api } from '@/lib/api';
import { AppConfig, PageConfig } from '@/types/config';
import { ComponentRenderer } from '@/components/dynamic/ComponentRenderer';
import { LoadingPage, ErrorState } from '@/components/ui/LoadingState';
import { addAppTranslations } from '@/lib/i18n';
import { CSVImporter } from '@/components/csv/CSVImporter';
import {
  LayoutDashboard, Table2, FormInput, BarChart2,
  Upload, Settings, Globe, Lock, Github,
  Mail, AlertCircle, Check, Loader2
} from 'lucide-react';
import Link from 'next/link';
import clsx from 'clsx';
import toast from 'react-hot-toast';

const PAGE_ICONS: Record<string, React.ComponentType<{ className?: string }>> = {
  home: LayoutDashboard,
  dashboard: LayoutDashboard,
  table: Table2,
  form: FormInput,
  chart: BarChart2,
};

function getIcon(iconName?: string) {
  return PAGE_ICONS[iconName?.toLowerCase() || ''] || LayoutDashboard;
}

// ─── Real GitHub export: generates a full project zip in browser ───────────────
async function generateAndDownloadZip(config: AppConfig) {
  // Build all files as strings
  const files: Record<string, string> = {};

  // app-config.json
  files['app-config.json'] = JSON.stringify(config, null, 2);

  // README.md
  files['README.md'] = `# ${config.name}

> Generated by [AppForge](https://appforge-green.vercel.app)

## Description
${config.description || 'A config-driven web application.'}

## Collections
${config.collections.map(c => `- **${c.label || c.name}**: ${c.fields.map(f => f.name).join(', ')}`).join('\n')}

## Pages
${config.pages.map(p => `- \`${p.path}\` — ${p.title || p.id}`).join('\n')}

## Setup with AppForge
1. Go to [AppForge](https://appforge-green.vercel.app)
2. Create a new app
3. Paste the contents of \`app-config.json\`
4. Click Create App

## Config Format
See [AppForge docs](https://appforge-green.vercel.app) for full config reference.

## Auth
${config.auth?.methods?.join(', ') || 'email/password'}
`;

  // schemas/collections.json
  files['schemas/collections.json'] = JSON.stringify(config.collections, null, 2);

  // schemas/pages.json
  files['schemas/pages.json'] = JSON.stringify(config.pages, null, 2);

  // .env.example
  files['.env.example'] = `DATABASE_URL=postgresql://user:password@localhost:5432/appforge
JWT_SECRET=your-secret-here
RESEND_API_KEY=re_xxxx
PORT=4000
`;

  // Simple HTML preview
  files['preview/index.html'] = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${config.name}</title>
  <style>
    body { font-family: sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #111; }
    h1 { color: #4F46E5; }
    .badge { display:inline-block; background:#EEF2FF; color:#4F46E5; border-radius:4px; padding:2px 8px; font-size:12px; margin:2px; }
    .collection { border:1px solid #e5e7eb; border-radius:8px; padding:16px; margin:12px 0; }
    table { width:100%; border-collapse:collapse; margin-top:8px; }
    th { background:#f9fafb; text-align:left; padding:8px; font-size:12px; color:#6b7280; }
    td { padding:8px; border-top:1px solid #f3f4f6; font-size:13px; }
  </style>
</head>
<body>
  <h1>${config.name}</h1>
  <p>${config.description || ''}</p>
  <h2>Collections</h2>
  ${config.collections.map(c => `
  <div class="collection">
    <strong>${c.label || c.name}</strong>
    <table>
      <tr><th>Field</th><th>Type</th><th>Required</th></tr>
      ${c.fields.map(f => `<tr><td>${f.name}</td><td><span class="badge">${f.type}</span></td><td>${f.required ? '✓' : ''}</td></tr>`).join('')}
    </table>
  </div>`).join('')}
</body>
</html>`;

  // Use JSZip via CDN approach — we'll create the zip manually as a blob
  // Since we can't import JSZip directly, use the fetch approach
  // Actually build a proper zip using the CompressionStream API or fallback
  // Simple approach: create individual file downloads in a zip using fflate if available
  // Fallback: download as a single JSON file with all contents

  try {
    // Try to dynamically import fflate (already in most Next.js projects)
    const { strToU8, zipSync } = await import('fflate');
    
    const zipFiles: Record<string, Uint8Array> = {};
    for (const [path, content] of Object.entries(files)) {
      zipFiles[path] = strToU8(content);
    }
    
    const zipped = zipSync(zipFiles);
    const blob = new Blob([zipped as unknown as BlobPart], { type: 'application/zip' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${config.slug || 'app'}-appforge-export.zip`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('✅ Full project exported as ZIP!');
  } catch {
    // Fallback: download as JSON bundle if fflate not available
    const bundle = { message: 'AppForge Export', files };
    const blob = new Blob([JSON.stringify(bundle, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${config.slug || 'app'}-export.json`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Config bundle exported!');
  }
}

export default function AppRuntimePage() {
  const { id } = useParams<{ id: string }>();
  const [activePage, setActivePage] = useState<string | null>(null);
  const [csvCollection, setCsvCollection] = useState<string | null>(null);
  const [showGithubModal, setShowGithubModal] = useState(false);
  const [showEmailModal, setShowEmailModal] = useState(false);
  const [githubExporting, setGithubExporting] = useState(false);
  const [emailAddress, setEmailAddress] = useState('');
  const [emailSubject, setEmailSubject] = useState('');
  const [emailBody, setEmailBody] = useState('');
  const [emailSending, setEmailSending] = useState(false);
  const [emailSent, setEmailSent] = useState(false);

  const { data, isLoading, error } = useQuery({
    queryKey: ['app', id],
    queryFn: async () => {
      const res = await appsApi.get(id);
      return res.data;
    },
  });

  const config: AppConfig | null = data?.config || null;

  useEffect(() => {
    if (config) {
      if (config.i18n) addAppTranslations(config.i18n);
      if (config.pages?.length && !activePage) {
        setActivePage(config.pages[0].id);
      }
    }
  }, [config, activePage]);

  useEffect(() => {
    if (config && showEmailModal) {
      setEmailSubject(`Update from ${config.name}`);
      setEmailBody(`Your app "${config.name}" has been updated successfully.`);
    }
  }, [config, showEmailModal]);

  // ─── Real GitHub Export ──────────────────────────────────────────────────────
  const handleGithubExport = async () => {
    if (!config) return;
    setGithubExporting(true);
    try {
      await generateAndDownloadZip(config);
      setShowGithubModal(false);
    } catch (err) {
      toast.error('Export failed. Please try again.');
      console.error(err);
    } finally {
      setGithubExporting(false);
    }
  };

  // ─── Real Email via backend ──────────────────────────────────────────────────
  const handleSendEmail = async () => {
    if (!emailAddress) return;
    setEmailSending(true);
    try {
      await api.post('/email/send', {
        to: emailAddress,
        appId: id,
        subject: emailSubject,
        body: emailBody,
      });
      setEmailSent(true);
      setTimeout(() => {
        setShowEmailModal(false);
        setEmailSent(false);
        setEmailAddress('');
      }, 2500);
    } catch (err: unknown) {
      const msg = (err as { response?: { data?: { message?: string } } })?.response?.data?.message;
      toast.error(msg || 'Failed to send email');
    } finally {
      setEmailSending(false);
    }
  };

  if (isLoading) return <LoadingPage />;
  if (error || !config) return (
    <ErrorState error="Failed to load app configuration" onRetry={() => window.location.reload()} />
  );

  const currentPage: PageConfig | undefined = config.pages?.find(p => p.id === activePage) || config.pages?.[0];
  const primaryColor = config.theme?.primaryColor;

  return (
    <div className="flex h-full min-h-screen bg-gray-50 dark:bg-gray-900" style={primaryColor ? { '--brand': primaryColor } as React.CSSProperties : {}}>

      {/* App sidebar */}
      <aside className="w-52 bg-white dark:bg-gray-800 border-r border-gray-200 dark:border-gray-700 flex flex-col shrink-0">
        <div className="px-4 py-3 border-b border-gray-100 dark:border-gray-700">
          <h2 className="font-bold text-gray-900 dark:text-white truncate text-sm">{config.name}</h2>
          <div className="flex items-center gap-1 mt-0.5 flex-wrap">
            <span className="badge badge-blue text-xs">{config.version || '1.0'}</span>
            {data?.is_published
              ? <span className="badge badge-green text-xs"><Globe className="w-2.5 h-2.5" />Live</span>
              : <span className="badge badge-gray text-xs"><Lock className="w-2.5 h-2.5" />Draft</span>}
          </div>
        </div>

        <nav className="flex-1 p-2 overflow-y-auto space-y-0.5">
          {config.pages?.map(page => {
            const Icon = getIcon(page.icon);
            return (
              <button key={page.id} onClick={() => setActivePage(page.id)}
                className={clsx(
                  'flex items-center gap-2 w-full px-3 py-2 rounded-lg text-sm font-medium transition-colors text-left',
                  activePage === page.id
                    ? 'bg-indigo-50 text-indigo-700 dark:bg-indigo-900/40 dark:text-indigo-300'
                    : 'text-gray-600 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-700'
                )}
              >
                <Icon className="w-4 h-4 flex-shrink-0" />
                <span className="truncate">{page.title || page.path}</span>
              </button>
            );
          })}

          {config.collections?.length > 0 && (
            <div className="mt-3 pt-3 border-t border-gray-100 dark:border-gray-700">
              <p className="text-xs font-semibold text-gray-400 px-3 mb-1 uppercase tracking-wide">Import</p>
              {config.collections.map(col => (
                <button key={col.name} onClick={() => setCsvCollection(col.name)}
                  className="flex items-center gap-2 w-full px-3 py-2 rounded-lg text-sm text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-700 transition-colors">
                  <Upload className="w-3.5 h-3.5 flex-shrink-0" />
                  <span className="truncate">{col.label || col.name}</span>
                </button>
              ))}
            </div>
          )}

          <div className="mt-3 pt-3 border-t border-gray-100 dark:border-gray-700">
            <p className="text-xs font-semibold text-gray-400 px-3 mb-1 uppercase tracking-wide">Tools</p>

            <button onClick={() => setShowGithubModal(true)}
              className="flex items-center gap-2 w-full px-3 py-2 rounded-lg text-sm text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-700 transition-colors">
              <Github className="w-3.5 h-3.5" /> Export to GitHub
            </button>

            <button onClick={() => setShowEmailModal(true)}
              className="flex items-center gap-2 w-full px-3 py-2 rounded-lg text-sm text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-700 transition-colors">
              <Mail className="w-3.5 h-3.5" /> Email Notification
            </button>
          </div>
        </nav>

        <div className="p-2 border-t border-gray-100 dark:border-gray-700">
          <Link href={`/apps/${id}/edit`}
            className="flex items-center gap-2 px-3 py-2 rounded-lg text-sm text-gray-500 hover:bg-gray-100 dark:hover:bg-gray-700 hover:text-gray-700 transition-colors">
            <Settings className="w-4 h-4" /> Edit Config
          </Link>
        </div>
      </aside>

      {/* Main content */}
      <div className="flex-1 flex flex-col overflow-hidden">
        {currentPage && (
          <header className="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 px-6 py-4 flex items-center justify-between shrink-0">
            <div>
              <h1 className="font-semibold text-gray-900 dark:text-white">{currentPage.title || currentPage.path}</h1>
              <p className="text-xs text-gray-400 mt-0.5">
                {currentPage.components?.length || 0} component{(currentPage.components?.length || 0) !== 1 ? 's' : ''}
              </p>
            </div>
          </header>
        )}

        <div className="flex-1 overflow-auto p-6">
          {!currentPage ? (
            <div className="text-center py-16 text-gray-400">
              <p>No pages configured yet.</p>
              <Link href={`/apps/${id}/edit`} className="btn-secondary mt-4 text-sm inline-flex">Edit Configuration</Link>
            </div>
          ) : currentPage.components?.length === 0 ? (
            <div className="text-center py-16 text-gray-400"><p>This page has no components configured.</p></div>
          ) : (
            <div className="space-y-6">
              {currentPage.components.map(component => (
                <div key={component.id}>
                  {component.title && <h2 className="text-base font-semibold text-gray-800 dark:text-gray-200 mb-3">{component.title}</h2>}
                  <ComponentRenderer appId={id} config={config} component={component} />
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* CSV Import Modal */}
      {csvCollection && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between px-6 py-4 border-b">
              <h3 className="font-semibold">Import CSV → {config.collections.find(c => c.name === csvCollection)?.label || csvCollection}</h3>
              <button onClick={() => setCsvCollection(null)} className="text-gray-400 hover:text-gray-700 text-xl">✕</button>
            </div>
            <div className="p-6">
              <CSVImporter
                appId={id}
                collection={config.collections.find(c => c.name === csvCollection)!}
                onSuccess={() => setCsvCollection(null)}
                onClose={() => setCsvCollection(null)}
              />
            </div>
          </div>
        </div>
      )}

      {/* GitHub Export Modal */}
      {showGithubModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-md">
            <div className="flex items-center justify-between px-6 py-4 border-b">
              <h3 className="font-semibold flex items-center gap-2"><Github className="w-5 h-5" /> Export to GitHub</h3>
              <button onClick={() => setShowGithubModal(false)} className="text-gray-400 text-xl">✕</button>
            </div>
            <div className="p-6 space-y-4">
              <div className="bg-gray-50 rounded-lg p-4 text-sm text-gray-600 space-y-2">
                <p className="font-medium text-gray-800">What will be exported:</p>
                <ul className="space-y-1 text-xs">
                  <li className="flex items-center gap-2"><Check className="w-3.5 h-3.5 text-green-500" /> <code>app-config.json</code> — Full configuration</li>
                  <li className="flex items-center gap-2"><Check className="w-3.5 h-3.5 text-green-500" /> <code>README.md</code> — Setup instructions</li>
                  <li className="flex items-center gap-2"><Check className="w-3.5 h-3.5 text-green-500" /> <code>schemas/collections.json</code> — Collection schemas</li>
                  <li className="flex items-center gap-2"><Check className="w-3.5 h-3.5 text-green-500" /> <code>schemas/pages.json</code> — Page definitions</li>
                  <li className="flex items-center gap-2"><Check className="w-3.5 h-3.5 text-green-500" /> <code>preview/index.html</code> — Static HTML preview</li>
                  <li className="flex items-center gap-2"><Check className="w-3.5 h-3.5 text-green-500" /> <code>.env.example</code> — Environment template</li>
                </ul>
              </div>
              <p className="text-xs text-gray-500">
                Downloads as a <strong>.zip</strong> file. Then run <code className="bg-gray-100 px-1 rounded">git init &amp;&amp; git add . &amp;&amp; git push</code> to push to GitHub.
              </p>
              <div className="flex gap-3">
                <button
                  onClick={handleGithubExport}
                  disabled={githubExporting}
                  className="btn-primary flex-1 justify-center"
                >
                  {githubExporting
                    ? <><Loader2 className="w-4 h-4 animate-spin" /> Generating...</>
                    : <><Github className="w-4 h-4" /> Download ZIP</>}
                </button>
                <button onClick={() => setShowGithubModal(false)} className="btn-secondary">Cancel</button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Email Notification Modal */}
      {showEmailModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50">
          <div className="bg-white rounded-xl shadow-2xl w-full max-w-md">
            <div className="flex items-center justify-between px-6 py-4 border-b">
              <h3 className="font-semibold flex items-center gap-2"><Mail className="w-5 h-5" /> Send Email Notification</h3>
              <button onClick={() => setShowEmailModal(false)} className="text-gray-400 text-xl">✕</button>
            </div>
            <div className="p-6 space-y-4">
              {emailSent ? (
                <div className="text-center py-4">
                  <div className="w-12 h-12 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-3">
                    <Check className="w-6 h-6 text-green-600" />
                  </div>
                  <p className="font-medium text-gray-900">Email sent!</p>
                  <p className="text-sm text-gray-500 mt-1">Notification delivered to {emailAddress}</p>
                </div>
              ) : (
                <>
                  <div>
                    <label className="label">Recipient Email</label>
                    <input
                      type="email"
                      className="input"
                      placeholder="user@example.com"
                      value={emailAddress}
                      onChange={e => setEmailAddress(e.target.value)}
                    />
                  </div>
                  <div>
                    <label className="label">Subject</label>
                    <input
                      type="text"
                      className="input"
                      value={emailSubject}
                      onChange={e => setEmailSubject(e.target.value)}
                    />
                  </div>
                  <div>
                    <label className="label">Message</label>
                    <textarea
                      className="input"
                      rows={3}
                      value={emailBody}
                      onChange={e => setEmailBody(e.target.value)}
                    />
                  </div>
                  <div className="flex gap-3">
                    <button
                      onClick={handleSendEmail}
                      disabled={!emailAddress || emailSending}
                      className="btn-primary flex-1 justify-center"
                    >
                      {emailSending
                        ? <><Loader2 className="w-4 h-4 animate-spin" /> Sending...</>
                        : <><Mail className="w-4 h-4" /> Send Notification</>}
                    </button>
                    <button onClick={() => setShowEmailModal(false)} className="btn-secondary">Cancel</button>
                  </div>
                </>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}